name: 'Infrastructure - Production'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Terraform formate
        id: formate
        run: |
          terraform fmt -diff -write=true -recursive .
          terraform fmt

      - name: install python packages & aws cli
        run: |
          python -m pip install --upgrade pip
          pip install pyhcl
          sudo apt update
          sudo apt install awscli -y

      - name: execute lint script 
        run: python Infrastructure_Definition/bin/lint.py
      
      - name: checking the last commit folder name 
        id: last_commit
        run: |
            last_commit=$(git log -1 --name-only --pretty=format:'' | xargs -n1 dirname | sort -u | head -1 | cut -d'/' -f1)
            if [[ $last_commit == "Stack_Definition"]]; then
              echo "::set-output name=folder::true"
            else
              echo "::set-output name=folder::false"
            fi 

      - name: executing the provider script
        if: steps.last_commit.outputs.folder == 'true'
        run: sh Infrastructure_Definition/bin/backend.sh
